### ISSUE TITLE
Deploy herbarium schema, needed to migrate captures with specied_id linked

### ISSUE THREAD

**Issue by Kpoke** [Greenstand/treetracker-herbarium-api#7]

**Comment by dadiorchen** [comment]
Any progress on this? any support needed? @Kpoke

**Comment by Kpoke** [comment]
@dadiorchen we will need terraform for this to work, to create the schema, the schema user and the schema passwords

**Comment by dadiorchen** [comment]
Okay, I will take it

**Comment by Kpoke** [comment]
Okay noted

**Comment by dadiorchen** [comment]
@Kpoke I have done this.
